### ISSUE TITLE
Emit state delta

### ISSUE THREAD

**Issue by jwulf** [ohager/nanoflux-fusion#4]
Can I have a Nanoflux-fusion store emit state deltas, in addition to emitting the complete state?

I want to trigger various side-effects on updates to different parts of my application state - aside from rendering.

For example, if I set the `username` in the store, I'd like to also save the username to localStorage. If I add a new Todo item, I'd like to push that item to a REST endpoint. 

I can do all of this as side-effects inside the Store, but I'd rather keep it pure.

**Comment by jwulf** [comment]
The other way I can think of doing it is to keep a copy of the application state outside the store and diff it with the new state received in my store subscription listener.

**Comment by ohager** [comment]
First of all, thanks for contribution. I suggest not to go with saving application state, or part of it, in another place (e.g. username in localStorage). This would break with the _Single Source of Truth_ concept. You already have the information stored, so saving it in another place to access it will bring more problems than it would resolve, i.e. you need to keep the localStorage in sync with the Flux Store. I recommend to subscribe to the store with your module/component and react on the username's change. Your component doesn't need to be a View/React component. 

Regarding the backend communication, you should go with HTTP requests inside an action (use promises..)...this is how it's done in Flux. The typical way to deal with Application State in Flux is to listen to state changes, and pick whatever you need. Of course, this way you'll have a lot of callbacks on state changes (especially if the app state is huge), but in my experience this isn't usually a performance bottleneck.

jfyi: One of the opened issues is to implement a middleware interface, which would attend your request in a generic way, i.e. you could implement a simple middleware for the diffing stuff. Maybe I have the time to implement it in January --- my spare time is quite limited at the moment (although I'm on vacation right now) :)

**Comment by ohager** [comment]
Hey @jwulf ... I just released a new version, with a simple middleware interface. Could be interesting for you, as it considers (implicitly) your delta stuff. Let me know, if there are some problems with it, or if you find other issues. Merry Xmas and a Happy New Year! 🎄🍾

**Comment by jwulf** [comment]
Hey, Happy New Year!

We went with Redux and PouchDB. We're using PouchDB to persist and replicate the state with the cloud, and hydrating the Redux store from PouchDB and updating Redux as the ViewModel from the PouchDB `onchange` handler.

I'd prefer to use Nanoflux-fusion because of its simplicity. We're using the Redux Chrome DevTool. Is there an equivalent tool for Nanoflux-fusion. Would it be difficult to build one?

**Comment by ohager** [comment]
@jwulf There's nothing like Redux DevTools for fusion yet. But I really think of build some inspection tool. It wouldn't be difficult...Initially, I think I'll go with a simple React Component that's capable of listen to a store. IMO it should be possible to do even a generic Flux Store Inspection. I have to check it out. I never developed a Chrome/FF plugin. This would be a step further to make the Inspector component available as browser plugin. I let you know about progress.

**Comment by ohager** [comment]
If there's nothing more to add, I'd like to close this issue.

@jwulf I started a new [project](https://github.com/ohager/nanoflux-devtool). Yet not usable, but time will come!
